// src/entities/file.entity.ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';
import { User } from './user.entity';
import { Room } from './room.entity';
import { Folder } from './folder.entity';

export enum FileType {
  DOCUMENT = 'document',
  IMAGE = 'image',
  SPREADSHEET = 'spreadsheet',
  PRESENTATION = 'presentation',
  PDF = 'pdf',
  OTHER = 'other',
}

export enum FileProcessingStatus {
  PENDING = 'pending',           // Just uploaded, not processed yet
  PROCESSING = 'processing',     // Embeddings being generated
  COMPLETED = 'completed',       // Successfully processed
  FAILED = 'failed',            // Processing failed
}

@Entity('files')
@Index(['uploader', 'folder'])
@Index(['room', 'folder'])
export class File {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  originalName: string; // given by user

  @Column()
  fileName: string; // Stored file name in s3(generated by system)

  @Column()
  filePath: string; // s3 url

  @Column()
  mimeType: string;

  @Column('bigint')
  size: number; // File size in bytes

  @Column({
    type: 'enum',
    enum: FileType,
  })
  type: FileType;

  @ManyToOne(() => User)
  uploader: User;

  @ManyToOne(() => Room, { nullable: true })
  room: Room | null;

  @ManyToOne(() => Folder, folder => folder.files, { nullable: true })
  folder: Folder | null;

  @Column({
    type: 'enum',
    enum: FileProcessingStatus,
    default: FileProcessingStatus.PENDING,
  })
  processingStatus: FileProcessingStatus;

  @Column({ type: 'int', nullable: true })
  chunksCreated: number | null; // Number of embeddings created

  @Column({ type: 'text', nullable: true })
  processingError: string | null; // Error message if failed

  @Column({ type: 'timestamp', nullable: true })
  processedAt: Date | null; // When embedding generation completed

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}